### ISSUE TITLE
Negative oriented AA are wrong

### ISSUE THREAD

**Issue by klamkiew** [desiro/silentMutations#2]
Hello there again ;)

It seems like the amino acids in the output file are switched between positive and negative strand:
```
Positive snip 1:   sl2a 25606-25623 UUUUUCUGCAGUGAGCUC FFCSEL
[...]
Positive sl2a_mut aa: UUCUUUUGUAGCGAGCUA LESCFF
Negative sl2a_mut aa: UAGCUCGCUACAAAAGAA FFCSEL
```

Shouldn't the amino acid `FFCSEL` be in the positive line?
Additionally: how are the negative-oriented AAs calculated? Because `UAG` would lead to a stop codon, not to phenylalanine.

**Comment by desiro** [comment]
You're right, they were switched, positive AA should be the one that's displayed as negative AA and vice versa. Fixed it.

Negative-oriented AAs are calculated by their reverse complement. So ```UAG``` -> ```GAU``` -> ```CUA``` -> leucine

* ```UAG CUC GCU ACA AAA GAA```
* ```AAG AAA ACA UCG CUC GAU```
* ```UUC UUU UGU AGC GAG CUA```
* ```-F- -F- -C- -S- -E- -L-```

**Comment by klamkiew** [comment]
but... if the sequence is the reverse complement, wouldn't the reading direction be switched as well?

So: `5-UAG-3` -> `3-GAU-5` -> `3-CUA-5` -> `5-AUC-3` --> isoleucine?

**Comment by desiro** [comment]
Yes, it will be switched, but this happes as soon as you take the complement. Regarding your example, you forgot to switch the 5'-3' to 3'-5' when you took the complement in step 3:

```5-UAG-3``` -> ```3-GAU-5``` -> ```5-CUA-3``` -> ```3-AUC-5```

**Comment by klamkiew** [comment]
True 😁
